name: Production Deployment

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Move to src directory
        run: cd src

      - name: Build Project
        run: npm run build  # Optional, if required

      - name: Deploy to Production
        run: echo "Deploying website from src directory"
